researchers=[
{"id":1,"name":"Dr. Anupom Das","title":"Health Informatics Researcher","institution":"Karolinska Institutet / Stockholm University","location":"Stockholm, Sweden","area":"Digital Health","photo":"https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80","bio":"Medical doctor and health informatics researcher interested in digital health, epidemiology, data science and AI in healthcare.","interests":["Digital Health","Health Informatics","Epidemiology","Explainable AI","Digital Health Equity"],"experience":"Clinical medicine, field epidemiology, public health research, disease surveillance and digital health research.","skills":["Python","R","SQL","HL7 FHIR","OpenEHR","DHIS2","Epidemiology","Machine Learning"],"outputs":["Digital Health Literacy among International Students — research project","Explainable AI for Disease Surveillance — research direction","CareBridge Network — digital elderly-care platform concept"],"linkedin":"https://www.linkedin.com/"},
{"id":2,"name":" Mahamaya Chakroborty","title":"Public Health Researcher","institution":"Research Institute","location":"Dhaka, Bangladesh","area":"Public Health","photo":"https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80","bio":"Researcher working on population health, health systems and community-based interventions.","interests":["Public Health","Health Systems","Community Health","Implementation Science"],"experience":"Community research, health-program evaluation and implementation studies.","skills":["Epidemiology","Biostatistics","Survey Research","Program Evaluation"],"outputs":["Community Health Intervention Study","Health Systems Evaluation"],"linkedin":"https://www.linkedin.com/"},
{"id":3,"name":"Dr. Erik Svensson","title":"Biomedical Data Scientist","institution":"Nordic Research Center","location":"Stockholm, Sweden","area":"AI & Data Science","photo":"https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80","bio":"Data scientist focused on machine learning, biomedical data and clinical decision support.","interests":["Machine Learning","AI in Medicine","Clinical Decision Support","Biomedical Informatics"],"experience":"Machine learning research using clinical and biomedical datasets.","skills":["Python","R","SQL","Machine Learning","Data Visualization"],"outputs":["Clinical Prediction Model","Explainable AI in Medicine"],"linkedin":"https://www.linkedin.com/"}
]

projects=[
{"title":"Digital Health Literacy Among International Students","description":"A cross-sectional project examining digital health literacy and barriers to Swedish digital health services.","area":"Digital Health","methods":["Survey research","Statistical analysis","Digital health literacy assessment"],"status":"Ongoing","contact":"Research project"},
{"title":"Explainable AI for Disease Surveillance","description":"Exploring explainable machine-learning methods for disease surveillance and outbreak-risk prediction.","area":"AI & Epidemiology","methods":["Machine learning","XAI","SHAP/LIME","Epidemiological data"],"status":"Ongoing","contact":"Research project"},
{"title":"CareBridge Network","description":"A digital ecosystem connecting elderly care seekers, guardians, caregivers, nurses, doctors and managers through coordinated care records and alerts.","area":"Elderly Care & Digital Health","methods":["Service design","Health informatics","Care coordination","Digital platform development"],"status":"Future","contact":"Concept / development"},
{"title":"AI-Assisted Elderly Care Risk Monitoring","description":"A future project exploring explainable risk alerts for falls, medication adherence and changes in health status.","area":"AI & Healthy Ageing","methods":["Predictive modelling","Explainable AI","Remote monitoring","Clinical decision support"],"status":"Future","contact":"Concept"}
]
